apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "app.name" . }}-env-file
spec:
  refreshInterval: {{ .Values.secret.refreshInterval }}         
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.secret.store }}       
  target:
    name: {{ include "app.name" . }}-env-file
    creationPolicy: Owner
  data:
  - secretKey: {{ .Values.envFile }}   
    remoteRef:
      key: {{ .Values.secret.items.file }}