apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}-app
spec:
  selector:
    {{- include "app.selectorLabels" . | nindent 8 }}-app
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.containerPort }}