env: ${ENV}
database:
  readReplicaDsn: ${POSTGRES_READ_DSN}
  writeReplicaDsn: ${POSTGRES_WRITE_DSN}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}

hashId:
  salt: ${HASH_ID_SALT}
  minLength: 7

rabbitmq:
  connectionString: ${RABBITMQ_DSN}
  serviceName: "ms-tech-talk"
  exchange:
    name: "ms-tech-talk"
    type: "topic"

  queues:
    - name: "ms-tech-talk.*"
      exchange: "ms-tech-talk"
      routingKey: "#"

    - name: "ms-tech-talk.ms-products.offer-created"
      exchange: "ms-products"
      routingKey: "offer-created"
      arguments:
        x-dead-letter-exchange: "dead-exchange"
        x-dead-letter-routing-key: "ms-tech-talk.ms-products.offer-created.dead"
        x-queue-type: "quorum"

    - name: "ms-tech-talk.ms-orders.order-created"
      exchange: "ms-products"
      routingKey: "offer-created"
      arguments:
        x-dead-letter-exchange: "dead-exchange"
        x-dead-letter-routing-key: "ms-tech-talk.ms-products.offer-created.dead"
        x-queue-type: "quorum"

      # Dead letter queues
    - name: "ms-tech-talk.ms-products.offer-created.dead"
      exchange: "dead-exchange"
      routingKey: "ms-tech-talk.ms-products.offer-created.dead"
      arguments:
        x-queue-type: "quorum"

    - name: "ms-tech-talk.ms-orders.order-created.dead"
      exchange: "dead-exchange"
      routingKey: "ms-tech-talk.ms-orders.order-created.dead"
      arguments:
        x-queue-type: "quorum"
